######################################################################
# Automatically generated by qmake (2.01a) dim. 20. févr. 00:56:05 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += src/label.h src/lorette.h src/matrice.h
FORMS += src/lorette.ui
SOURCES += src/label.cpp src/lorette.cpp src/main.cpp src/matrice.cpp
