######################################################################
# Automatically generated by qmake (2.01a) sam. 19. févr. 22:33:51 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += src/label.h src/mainwindow.h src/matrice.h
FORMS += src/mainwindow.ui
SOURCES += src/label.cpp src/main.cpp src/mainwindow.cpp src/matrice.cpp
